### ISSUE TITLE
Whether the key of Attachable should support type information to prevent collision？

### ISSUE THREAD

**Issue by driventokill** [foldright/inspectable-wrappers#4]
The attachable implementation uses `String` as key type. If someone selects the same string in the top layer, the value will be shaded in the lower layer. I don't think this is the proper way. Perhaps we ought to consider the solution in the context of golang. Everyone uses their own primary type as key type and will never conflict with anyone else.

**Comment by oldratlee** [comment]
> The attachable implementation uses `String` as key type. If someone selects the same string in the top layer, the value will be shaded in the lower layer. I don't think this is the proper way.

Good concern 👍❤️

Using `String` is just a simple implementation.
(Simplicity is not bad, but not too simple 🤣)

I think the shadowing problem can be resolved by the key name plan like domain name, java package name, etc. 

A better and simple solution is welcomed. 💕  @driventokill
